# -*- coding: utf-8 -*-
"""Copy of data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q93sreiuiEbmLukAUyBTq5XEFwZAKDbu

## Tujuan Visualiasi

1. Exploratory :
- Mencari insight dari data.
- Tidak terlalu mementingkan estetik asal analis dapat mengerti.
- Menggunakan jenis visualisasi yang lebih advanced
- Berkenalan dengan data

2. Explanatory :
- Menyampaikan insight dari data
- Estetik diutamakan

## Univariate I

data hanya terdiri dari satu variabel (only x value)
1. Line Plots
2. Histograms
3. Box Plots
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/sushantag9/Supermarket-Sales-Data-Analysis/master/supermarket_sales%20-%20Sheet1.csv")
df.head()

df.info()

df["DateTime"] = pd.to_datetime(df["Date"] + " " + df["Time"])
df

df.info()

df.drop(columns=["Date","Time"],inplace=True)
df.info()

"""### Line Plot"""

df["hour"] = df["DateTime"].dt.hour #menambah kolom jam
df["day"] = df["DateTime"].dt.day #menambah kolom hari
df["weekday"] = df["DateTime"].dt.weekday #menambah kolom week
df["month"] = df["DateTime"].dt.month #menambah kolom bulan

df.head()

df["day"] = df["DateTime"].dt.day #menambah kolom hari

df_plot = df.groupby("day").agg({"Quantity":"sum"}).reset_index() # jumlah tiap hari

df

df_plot

sns.lineplot(data=df_plot,x="day",y="Quantity")
plt.title("Quantity in day")
plt.show()

"""## Histograms"""

df.head()

df.info()

sns.histplot(df,x="Rating")

sns.histplot(data=df, x='Rating', bins=20)

"""## Box Plots"""

sns.boxplot(data=df,y="Rating")

sns.boxplot(data=df,y="Tax 5%")